---
title: "Geoplotting Power Plants"
author: "Harsh Sharda"
date: "12/15/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggmap)
library(dplyr)
library(lubridate)
library(stringr)
library(plotly)
library(raster)
library(spData)
library(sf)
library(htmltools)
#library(spDataLarge)
library(tmap)    # for static and interactive maps
library(leaflet) # for interactive maps
library(mapview) # for interactive maps
library(maps)
```


```{r}
powerplant_viz <- read.csv("Data/Powerplant/power_plant_data_locations.csv")
powerplant_emissions <- read.csv("Data/Powerplant/power_plants_locations_emissions.csv")
map_world <- st_read("Data/Shapefile/TM_WORLD_BORDERS-0.3.shp")
```


```{r}
is.element(powerplant_emissions$cou,map_world$ISO3)
# Number 86 is not matching Kosovo
powerplant_emissions$ISO3[86]
```

```{r}
is.element(map_world$ISO3,powerplant_emissions$ISO3)
```

```{r}
map_world <- subset(map_world,is.element(map_world$ISO3,powerplant_emissions$ISO3))
```

```{r}
powerplant_emissions <- subset(powerplant_emissions,is.element(powerplant_emissions$ISO3,map_world$ISO3)) %>%
  .[order(match(powerplant_emissions$ISO3,map_world$ISO3)),]
```

```{r}
bins <- c(0, 2, 4, 6, 8, 10, 12, Inf)
pal <- colorBin(palette = "YlOrRd",
                    domain = powerplant_emissions$emissions_total_2014,
                    bins = bins * 10^6)
pal2 <- colorFactor(palette = c("firebrick3","darkolivegreen3"), domain = powerplant_viz$fuel_category)

```


```{r}
label <- paste("<p>","Country Name: ",powerplant_emissions$country_name,"</p>",
               "<p>","Emissions: ",powerplant_emissions$emissions_total_2014,"</p>",
               sep = "")
```

```{r}
m <- leaflet(powerplant_viz) %>%  addTiles() %>%
  setView(0,0, zoom = 0.9) %>%
  addPolygons(data = map_world1, weight = 1, smoothFactor = 0.5, color = "white",
              fillOpacity = 0.8, fillColor = ~pal(powerplant_emissions$emissions_total_2014),
              label = lapply(label, HTML),
              group = "GHG Emissions") %>%
  addLegend(pal = pal,
            values = powerplant_emissions$emissions_total_2014,
            opacity = 0.7,
            position = "topright",
            title = "GHG Emissions") %>%
    addLegend(pal = pal2,
            values = powerplant_viz$fuel_category,
            opacity = 0.7,
            position = "bottomright",
            title = "Fuel Category") %>%
  addCircleMarkers(lat = ~latitude, lng = ~longitude,
                   popup = ~name_type,
                   radius = ~0.0000001,
                   color = ~pal2(powerplant_viz$fuel_category),
                   fillOpacity = 0.8,
                   group = "Power Plants") %>%
  addLayersControl(overlayGroups = c("GHG Emissions", "Power Plants"),
                   options = layersControlOptions(collapsed = FALSE),
                   position = "bottomleft")
m
```


## Other Ideas & Extra Codes (Not a part of the main visualizations):


```{r}
terrain <- get_stamenmap(bbox = c(left = -124.848974, 
                              bottom = 24.396308, 
                              right =-66.885444, 
                              top = 49.384358), zoom = 5, maptype = "terrain")
```

```{r}
ggmap(terrain) + geom_point(data = powerplant_viz,
                            # Define your dataset
                            aes(x = longitude, y = latitude), # Select the latitude and longitude columns
                            size = 1, # Set the point size
                            shape=19, # Select the desired shape
                            color='red', # Set the desired color
                            alpha=0.1)
```

```{r}
p <- ggplot() +  geom_polygon(data=powerplant_viz, aes(x=longitude, y=latitude),  color="white", lwd = .25)
 
ggplotly(p)
```

```{r}
mapWorld = map("world", fill = TRUE, plot = FALSE)
leaflet(data = mapStates) %>% addTiles() %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE)
```

```{r}
leaflet(data = mapWorld) %>% addTiles() %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE) %>%
  addCircles(data = powerplant_viz, lat = ~latitude, lng = ~longitude, popup = ~name) %>%
  addCircleMarkers(radius = 5)
```

```{r}
pal <- colorFactor(palette = c("darkolivegreen3", "firebrick3"), domain = powerplant_viz$fuel_category)

leaflet(powerplant_viz) %>%  addTiles() %>%
  addCircleMarkers(lat = ~latitude, lng = ~longitude, popup = ~name, radius = ~0.0000001,color = ~pal(fuel_category), fillOpacity = 0.8)
```

```{r}
tm_shape(world) + tm_polygons(col = "Median_income")
#+ tm_symbols(col = "black", border.col = "white", size = "capacity_mw")
```

```{r}
m <- leaflet(powerplant_viz) %>%  addTiles() %>%
  addPolygons(data = map_world1, weight = 1, smoothFactor = 0.5, color = "white",
              fillOpacity = 0.8, fillColor = ~pal(powerplant_emissions1$emissions_total_2014)
#              highlight = highlightOptions(
#                weight = 5,
#                color = "gray",
#                dashArray = ""
#                fillOpacity = 0.7,
#                bringToFront = TRUE)
              ) %>%
  addCircleMarkers(lat = ~latitude, lng = ~longitude, popup = ~name, radius = ~0.0000001,color = ~pal2(powerplant_viz$fuel_category), fillOpacity = 0.8)
m
```