---
title: "Sunburst_powerplants"
author: "Harsh Sharda"
date: "12/16/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(plotly)
library(sunburstR)
library(d3r)
library(janitor)
```

```{r}
powerplant_viz <- read.csv("Data/Powerplant/power_plant_data_locations.csv")
```

```{r}
check1 <- powerplant_viz %>%
  group_by(country_name,fuel_category,primary_fuel) %>%
  summarize(tot_capacity = sum(round(capacity_mw)))

grandTotals <- check1 %>%
  group_by(fuel_category,primary_fuel) %>%
  summarize(Name = "All",
            tot_capacity = sum(round(tot_capacity))) %>%
  rename(country_name = Name) %>%
  bind_rows(check1)
```

```{r}
ls <- grandTotals %>% spread(primary_fuel, tot_capacity, fill = 0) %>%
  names(.) %>% .[3:17]
```

```{r}
name_country = "India"

sum_non_renew <- grandTotals %>% filter(fuel_category == "Non-renewable" & country_name == name_country) %>% summarise(sum = sum(tot_capacity))

sum_renew <- grandTotals %>% filter(fuel_category == "Renewable" & country_name == name_country) %>% summarise(sum = sum(tot_capacity))

sum_total <- grandTotals %>% filter(country_name == name_country) %>%
  group_by(country_name) %>% summarise(sum = sum(tot_capacity))
```

```{r}
values <-c(sum_total$sum,sum_non_renew$sum,sum_renew$sum)
```


```{r}
for (val in ls){
  a <- grandTotals %>% filter(primary_fuel == val & country_name == name_country) %>%
    summarise(sum = sum(tot_capacity))
  values = append(round(values), round(a$sum))
}

labels <- c("All","Non-renewable", "Renewable", ls)
parents <- c("","All","All","Renewable",
             "Non-renewable","Non-renewable","Non-renewable","Renewable",
             "Renewable","Renewable","Non-renewable","Non-renewable",
             "Non-renewable","Renewable","Renewable","Non-renewable",
             "Renewable","Renewable")
```



```{r}
index_nums <- which(values %in% 0)

if(length(index_nums)!=0){
  values <- values[-index_nums]
  labels <- labels[-index_nums]
  parents <- parents[-index_nums]
}
```


```{r}
p <- plot_ly(
  labels = labels,
  parents = parents,
  values = values,
  type = 'sunburst',
  branchvalues = 'Total'
) %>%
    layout(title = 'Fuel Category')
p
```

## Extra Codes

```{r}
p <- plot_ly(
  labels = c("Eve", "Cain", "Seth", "Enos", "Noam", "Abel", "Awan", "Enoch", "Azura"),
  parents = c("", "Eve", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve"),
  values = c(10, 14, 12, 10, 2, 6, 6, 4, 4),
  type = 'sunburst',
  textinfo = "label+percent",
  hoverinfo = "percent root"
)
p
```


```{r}
tree <- d3_nest(check2, value_cols = "tot_capacity")
sb2 <- sund2b(tree, width="100%")
sb2
```

```{r}
q <- plot_ly(
  labels = c("All","Renewable","Non-Renewable","Hydro"),
  parents = c("","All","All","Renewable"),
  values = c(30.556,10.556,20,5),
  type = 'sunburst',
  branchvalues = "total"
)
q
```

```{r}
values
sum(values[2:3])
```

```{r}

```
```{r}
p <- plot_ly(
  labels = labels_check,
  parents = parents_check,
  values = values_check,
  type = 'sunburst',
  branchvalues = "total"
) %>%
    layout(title = 'Fuel Category')
p
```

## Version 2:

```{r}
name_country = "India"
n <- grandTotals %>% filter(country_name == name_country)
```

```{r}
n_spreaded <- n %>% spread(primary_fuel, tot_capacity, fill = 0)
ls_2 <- names(n_spreaded)
ls1_2 <- ls_2[3:length(ls_2)]
```

```{r}
sum_non_renew <- grandTotals %>% filter(fuel_category == "Non-renewable" & country_name == name_country) %>% summarise(sum = sum(tot_capacity))

sum_renew <- grandTotals %>% filter(fuel_category == "Renewable" & country_name == name_country) %>% summarise(sum = sum(tot_capacity))

sum_total <- grandTotals %>% filter(country_name == name_country) %>%
  group_by(country_name) %>% summarise(sum = sum(tot_capacity))

values <-c(sum_total$sum,sum_non_renew$sum,sum_renew$sum)

```

```{r}
for (val in ls1_2){
  a <- grandTotals %>% filter(primary_fuel == val & country_name == name_country) %>%
    summarise(sum = sum(tot_capacity))
  values = append(round(values), round(a$sum))
}

labels <- c("All","Non-Renewable", "Renewable", ls1_2)
parents <- c("","All","All","Renewable",
             "Non-Renewable","Non-Renewable","Non-Renewable","Renewable",
             "Renewable","Renewable","Non-Renewable")

values
ls_2

,"Non-Renewable",
             "Non-Renewable","Renewable","Renewable","Renewable",
             "Renewable","Renewable"
```

```{r}
p <- plot_ly(
  labels = labels,
  parents = parents,
  values = values,
  type = 'sunburst',
  branchvalues = "total"
) %>%
    layout(title = 'Fuel Category')
p
```


